server.port=8090
spring.application.name=orders

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui-custom.html

spring.profiles.active=dev

spring.mongodb.host=mongo1
spring.mongodb.port=27017
spring.mongodb.database=mongodb
spring.mongodb.username=user
spring.mongodb.password=pwd
spring.mongodb.replica-set-name=rs0
spring.mongodb.representation.uuid=standard
spring.mongodb.authentication-database=admin
#maxConnectionPoolSize equals 100 by default in mongodb
